version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_instance
    ports:
      - "5672:5672" # RabbitMQ messaging port
      - "15673:15672" # RabbitMQ management UI port (changed to avoid conflict)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: redis_instance
    ports:
      - "6379:6379" # Redis default port
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
